### ISSUE TITLE
[BUG] NPM INSTALL

### ISSUE THREAD

**Issue by ImNotKilian** [cityssm/parking-ticket-system#294]
Every time I run NPM INSTALL i get this:

Cannot find package 'connect-sqlite3'

**Comment by dangowans** [comment]
Thanks for testing (or trying to test) things out, : )

That kind of sounds like a hiccup with npm.  Regardless, I updated the dependencies.  Hopefully after getting the latest code, `npm install` will find it.

SQLite packages also are sometimes picky when it comes to operating systems.  The application is primarily being developed on and deployed to Windows.  It should work on Linux and others, but it's possible there could be something I missed there.

**Comment by dangowans** [comment]
The dependency that was hanging up your install is no longer a dependency.  Hopefully that resolves your issue.
