### ISSUE TITLE
[BUG]  Config-defaults file does not exist

### ISSUE THREAD

**Issue by NulledCodeDev** [cityssm/parking-ticket-system#446]
**What seems to be the problem?**

 
config-defaults file does not exist

**How can I recreate this problem?**

**What did you expect to happen?**

**Do you have pictures of the problem?**

**What kind of device and web browser are you using?**

**Is there anything else you can offer that might help?**

**Comment by dangowans** [comment]
Thanks for the issue.  You are right, `data/config-default.js` does not exist.  I'm guessing it got renamed, and the documentation didn't get updated.  Sorry for the confusion.

`data/configOntario.js` is a good starting point, in Ontario, Canada at least.

I'll update the documentation to clear things up.
